### PR TITLE
Updated personalized install code to use github.io

### PR DESCRIPTION
**Pull request by ilivewithian**

### CODE REVIEW

**Comment by groundh0g** [comment]
@plusjade, this is a tweak to gh-pages. Isn't the generator on Ruhoh? If so, it's as simple as tweaking "github.com" to be "github.io". If not, I'll merge this PR. Assuming edits won't take effect from the gh-pages branch, though.

**Comment by ilivewithian** [comment]
@groundh0g is this project dead?

**Comment by groundh0g** [comment]
@ilivewithian Nope. Sorry for inactivity recently. Started new job in another state and have been travelling 100%. We close on our new house in GA on the 16th, so I'm hoping things will settle down shortly thereafter.

**Comment by groundh0g** [comment]
I'm merging now. Don't think it will have any effect, though. Pretty sure the jekyll-bootstrap site is powered by @plusjade's static blog engine, Ruhoh.

**Pull request merged**
