### PR TITLE
Added tag cloud helper. Split tutorials.

### PR DESCRIPTION
**Pull request by dfrencham**
Added a tag cloud helper for liquid.
Split tutorial into 4 posts to demonstrate Jekyll features (such as tags, post list).

(This pull request is a resubmission on the correct branch this time).

### CODE REVIEW

**Comment by groundh0g** [comment]
After a quick review, I like what I see. Unfortunately, `jb-development` isn't used for development now (I'd like it to be, asap), so I'll pull this into `master` for the current release.

Was going to split into two separate commits, but I see why @dfrencham decided to make it one -- the splitting of the tutorials into separate posts provides content for the tag cloud. Cool addition. Thanks for contributing!

**Comment by groundh0g** [comment]
Looks like slugize has become slugify? Will see how that affects things when I integrate into `master`.

**Comment by groundh0g** [comment]
Changes made to local repo. Pushing this weekend. 

Cloud example is included in bootstrap-3 template, but commented out.

**Comment by dfrencham** [comment]
@groundh0g hi mate - I'm glad this was useful for you. :)

**Pull request closed without merging**
